# Generated by Django 2.2.14 on 2020-07-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200713_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
