# Generated by Django 2.2.10 on 2020-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
