# Generated by Django 2.2.10 on 2020-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200314_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
