# Generated by Django 2.2.10 on 2020-03-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200314_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_at',
        ),
    ]
