# Generated by Django 2.2.10 on 2020-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_newsletter_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
