# Generated by Django 2.2.11 on 2020-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200323_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='contents',
            field=models.FileField(upload_to='uploaded_newsletters/'),
        ),
    ]
