# Generated by Django 2.2.11 on 2020-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_newsletter_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to='email_attachments/'),
        ),
    ]
