# Generated by Django 2.2.11 on 2020-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200328_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video',
            field=models.TextField(blank=True, default='', help_text='This is for a single YouTube video to be displayed at the top of a post. To get the code, go to the video on YouTube, click on the "Share" option, and then click on "Embed". Copy and paste the code here. If you want the video to look good on phones, change the number in quotes for "width" from "560" to "75%" (It is at the very beginning of the code you posted).', null=True),
        ),
    ]
